### ISSUE TITLE
Показания датчика параметра среды BME680 

### ISSUE THREAD

**Issue by Timofey-arch** [Electro98/cyber-growbox-2077#15]
## Описание проблемы
GrowBox будет содержать датчик, который передает параметры качества воздуха, а именно:
* Температура воздуха
* Содержание газов в воздухе (летучие органические соединения)
* Барометрическое давление 
* Влажность воздуха
## Возможная реализация 
Для удобной работы с остальными датчиками предлагается оформить процедуру чтения данных с датчика BME680 при помощи функции `getAirParametrs`, которая возвращает значения с плавающей точкой всех вышеперечисленных параметров качества воздуха.
Данные с датчиков необходимо выводить в Serial порт.
## Подключение
* Arduino Nano 
* BME680 (датчик параметра среды)

Ссылка на интернет-ресурс с подробным описанием работы данного датчика и схемой подключения к плате [BME680][1]

[1]: https://umnyjdomik.ru/cjmcu-680-bme680-datchik-kachestva-vozduha-i-okruzhajushhej-obstanovki-gazy-davlenie-vlazhnost-temperatura.html

**Comment by redb0** [comment]
Это issue дублирует ранее созданное issue #27, Там более подробно описаны требования, поэтому закрываю это issue.
