### ISSUE TITLE
Переоформление функции для датчиков

### ISSUE THREAD

**Issue by Electro98** [Electro98/cyber-growbox-2077#17]
# Переоформление функции для датчиков
## Описание проблемы

Функции многих датчиков были реализованы, однако, их реализация не позволяет включить эти функции через команду препроцессора `<include>`.

## Предлагаемая реализация

Предлагается переоформить код файлов содержащих эти функции, для возможности последующего импорта этих функций в основной код.

**Comment by redb0** [comment]
@SerLap-ctrl, ожидается удаление файла `Tds_Meter.cpp` и изменение константы `PINSENSOR` в `setup.h`
