### ISSUE TITLE
Написание тестового сервера для взаимодействия с Wi-fi модулем

### ISSUE THREAD

**Issue by Timofey-arch** [Electro98/cyber-growbox-2077#22]
## Описание проблемы

Для удобного мониторинга, а также сбора, хранения и дальнейшего анализа информации, собираемой датчиками, необходимо реализовать централизованную систему в виде веб-сервера. 

## Возможная реализация

Сервер должен обращаться к устройству посредством `GET` и `POST` запросов. Необходимо реализовать следующие запросы:
- `GET` запрос на получения данных с датчиков (независимо от состояния таймера), ответ на этот запрос должен содержать данные в `json` формате вида:
```json
{
    "parameter": "value_int_float_str", 
}
```
- `POST`/`GET` запрос на установку таймера для сбора данных с датчиков
- `GET` запрос на включение/выключение устройства (лампы, насоса и др.)
- `GET` запрос на подъем/опускание платформы с лампами

Помимо непосредственных запросов устройство должно отсылать данные на сервер в виде `POST` запросов по таймеру с помощью часов реального времени `DS3231` и модуля Wi-Fi `esp-01`. Со стороны сервера нужно обеспечить прием этих запросов и отображение информации на страничке (для начала без сохранения в БД, возможно, реализовать сохранение в списки или словари python).

Реализовать отображение линейных графиков с помощью Dash. Подробнее о линейных графиках смотри в [документации к Dash](https://plotly.com/python/line-charts/). О размещении графиков на странице можно ознакомиться в [документации](https://dash.plotly.com/interactive-graphing).

При реализации запросов желательно воспользоваться представлениями в виде классов. Это позволяет сделать [`flask.views.MethodView`](https://flask.palletsprojects.com/en/1.1.x/views/#method-based-dispatching).

## Инструментарий

- Flask (для реализации веб-сервера)
- Dash (для создания дашбордов мониторинга системы)
- pandas (для удобной работы с данными, по ситуации)

**Comment by Electro98** [comment]
Требуется переоформить это issue, так как оно стало не действительным. Предлагается или переопределить задачу, или удалить это issue.

**Comment by redb0** [comment]
Возьмусь за обновление этого issue
